/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin.index'
import { Route as AppCoteriesIndexRouteImport } from './routes/_app/coteries.index'
import { Route as AppCoteriesCoterieIdRouteImport } from './routes/_app/coteries.$coterieId'
import { Route as AppCoteriesNewRouteImport } from './routes/_app/coteries.new'
import { Route as AppMarketplaceIndexRouteImport } from './routes/_app/marketplace.index'
import { Route as AppNotificationsIndexRouteImport } from './routes/_app/notifications.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const AppCoteriesIndexRoute = AppCoteriesIndexRouteImport.update({
  id: '/coteries/',
  path: '/coteries/',
  getParentRoute: () => AppRoute,
} as any)
const AppCoteriesCoterieIdRoute = AppCoteriesCoterieIdRouteImport.update({
  id: '/coteries/$coterieId',
  path: '/coteries/$coterieId',
  getParentRoute: () => AppRoute,
} as any)
const AppCoteriesNewRoute = AppCoteriesNewRouteImport.update({
  id: '/coteries/new',
  path: '/coteries/new',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketplaceIndexRoute = AppMarketplaceIndexRouteImport.update({
  id: '/marketplace/',
  path: '/marketplace/',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsIndexRoute = AppNotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/coteries/$coterieId': typeof AppCoteriesCoterieIdRoute
  '/coteries/new': typeof AppCoteriesNewRoute
  '/admin/': typeof AppAdminIndexRoute
  '/coteries/': typeof AppCoteriesIndexRoute
  '/marketplace/': typeof AppMarketplaceIndexRoute
  '/notifications/': typeof AppNotificationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/coteries/$coterieId': typeof AppCoteriesCoterieIdRoute
  '/coteries/new': typeof AppCoteriesNewRoute
  '/admin': typeof AppAdminIndexRoute
  '/coteries': typeof AppCoteriesIndexRoute
  '/marketplace': typeof AppMarketplaceIndexRoute
  '/notifications': typeof AppNotificationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/coteries/$coterieId': typeof AppCoteriesCoterieIdRoute
  '/_app/coteries/new': typeof AppCoteriesNewRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/coteries/': typeof AppCoteriesIndexRoute
  '/_app/marketplace/': typeof AppMarketplaceIndexRoute
  '/_app/notifications/': typeof AppNotificationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/coteries/$coterieId'
    | '/coteries/new'
    | '/admin/'
    | '/coteries/'
    | '/marketplace/'
    | '/notifications/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/coteries/$coterieId'
    | '/coteries/new'
    | '/admin'
    | '/coteries'
    | '/marketplace'
    | '/notifications'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/coteries/$coterieId'
    | '/_app/coteries/new'
    | '/_app/admin/'
    | '/_app/coteries/'
    | '/_app/marketplace/'
    | '/_app/notifications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coteries/': {
      id: '/_app/coteries/'
      path: '/coteries'
      fullPath: '/coteries/'
      preLoaderRoute: typeof AppCoteriesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coteries/$coterieId': {
      id: '/_app/coteries/$coterieId'
      path: '/coteries/$coterieId'
      fullPath: '/coteries/$coterieId'
      preLoaderRoute: typeof AppCoteriesCoterieIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coteries/new': {
      id: '/_app/coteries/new'
      path: '/coteries/new'
      fullPath: '/coteries/new'
      preLoaderRoute: typeof AppCoteriesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketplace/': {
      id: '/_app/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof AppMarketplaceIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications/': {
      id: '/_app/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof AppNotificationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCoteriesCoterieIdRoute: typeof AppCoteriesCoterieIdRoute
  AppCoteriesNewRoute: typeof AppCoteriesNewRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppCoteriesIndexRoute: typeof AppCoteriesIndexRoute
  AppMarketplaceIndexRoute: typeof AppMarketplaceIndexRoute
  AppNotificationsIndexRoute: typeof AppNotificationsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCoteriesCoterieIdRoute: AppCoteriesCoterieIdRoute,
  AppCoteriesNewRoute: AppCoteriesNewRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppCoteriesIndexRoute: AppCoteriesIndexRoute,
  AppMarketplaceIndexRoute: AppMarketplaceIndexRoute,
  AppNotificationsIndexRoute: AppNotificationsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
