/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppCoteriesIndexRouteImport } from './routes/_app/coteries.index'
import { Route as AppCoteriesCoterieIdRouteImport } from './routes/_app/coteries.$coterieId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCoteriesIndexRoute = AppCoteriesIndexRouteImport.update({
  id: '/coteries/',
  path: '/coteries/',
  getParentRoute: () => AppRoute,
} as any)
const AppCoteriesCoterieIdRoute = AppCoteriesCoterieIdRouteImport.update({
  id: '/coteries/$coterieId',
  path: '/coteries/$coterieId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/coteries/$coterieId': typeof AppCoteriesCoterieIdRoute
  '/coteries/': typeof AppCoteriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/coteries/$coterieId': typeof AppCoteriesCoterieIdRoute
  '/coteries': typeof AppCoteriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/coteries/$coterieId': typeof AppCoteriesCoterieIdRoute
  '/_app/coteries/': typeof AppCoteriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/coteries/$coterieId' | '/coteries/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/coteries/$coterieId' | '/coteries'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/coteries/$coterieId'
    | '/_app/coteries/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/coteries/': {
      id: '/_app/coteries/'
      path: '/coteries'
      fullPath: '/coteries/'
      preLoaderRoute: typeof AppCoteriesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coteries/$coterieId': {
      id: '/_app/coteries/$coterieId'
      path: '/coteries/$coterieId'
      fullPath: '/coteries/$coterieId'
      preLoaderRoute: typeof AppCoteriesCoterieIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCoteriesCoterieIdRoute: typeof AppCoteriesCoterieIdRoute
  AppCoteriesIndexRoute: typeof AppCoteriesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCoteriesCoterieIdRoute: AppCoteriesCoterieIdRoute,
  AppCoteriesIndexRoute: AppCoteriesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
